# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolgtext1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BolgPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('body', models.TextField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
