# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-14 09:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bolgtext1', '0004_richang_richnagadmin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='richnagadmin',
        ),
    ]
