# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-15 05:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolgtext1', '0005_delete_richnagadmin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('body', models.TextField()),
                ('downurl', models.TextField()),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'ordering': ('-timestamp',),
            },
        ),
        migrations.AlterModelOptions(
            name='bolgpost',
            options={'ordering': ('-timestamp',)},
        ),
        migrations.AlterModelOptions(
            name='richang',
            options={'ordering': ('-timestamp',)},
        ),
    ]
