# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-24 02:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bolgtext1', '0006_auto_20170415_1334'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='richang',
            options={},
        ),
    ]
